// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserPunchApi.Data;

#nullable disable

namespace UserPunchApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.18");

            modelBuilder.Entity("UserPunchApi.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("UserPunchApi.Models.LeaveRequest", b =>
                {
                    b.Property<long>("LeaveRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LeaveReason")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LeaveRequestId");

                    b.HasIndex("UserId");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("UserPunchApi.Models.PunchRecord", b =>
                {
                    b.Property<long>("PunchRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModificationReason")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ModifiedByManagerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PunchInTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PunchOutTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PunchRecordId");

                    b.HasIndex("ModifiedByManagerId");

                    b.HasIndex("UserId", "PunchInTime")
                        .IsUnique();

                    b.ToTable("PunchRecords");
                });

            modelBuilder.Entity("UserPunchApi.Models.Schedule", b =>
                {
                    b.Property<long>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CreatedByManagerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ShiftDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ScheduleId");

                    b.HasIndex("CreatedByManagerId");

                    b.HasIndex("UserId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("UserPunchApi.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UserPunchApi.Models.LeaveRequest", b =>
                {
                    b.HasOne("UserPunchApi.Models.User", "User")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserPunchApi.Models.PunchRecord", b =>
                {
                    b.HasOne("UserPunchApi.Models.User", "ModifiedByManager")
                        .WithMany()
                        .HasForeignKey("ModifiedByManagerId");

                    b.HasOne("UserPunchApi.Models.User", "User")
                        .WithMany("PunchRecords")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModifiedByManager");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserPunchApi.Models.Schedule", b =>
                {
                    b.HasOne("UserPunchApi.Models.User", "CreatedByManager")
                        .WithMany()
                        .HasForeignKey("CreatedByManagerId");

                    b.HasOne("UserPunchApi.Models.User", "User")
                        .WithMany("Schedules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByManager");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserPunchApi.Models.User", b =>
                {
                    b.HasOne("UserPunchApi.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("UserPunchApi.Models.Department", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("UserPunchApi.Models.User", b =>
                {
                    b.Navigation("LeaveRequests");

                    b.Navigation("PunchRecords");

                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
